### ISSUE TITLE
The ReadToEndAsync hangs 

### ISSUE THREAD

**Issue by unliftedq** [markashleybell/ReadRawRequestBodyExample#1]
Some of requests hangs at ReadToEndAsync, and then throw the following exceptions, the error rate is very low, but want to know the root cause and solution

```bash
System.IO.IOException
 ---> Microsoft.AspNetCore.Server.HttpSys.HttpSysException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadToEndAsyncInternal(CancellationToken cancellationToken)
```

**Comment by markashleybell** [comment]
Hi—I'm sorry, but this repository was just intended to be a very, very basic example, and not something I offer debugging support for.

You don't include any context either, so this could be due to any one of a _huge_ number of reasons. A quick Google for the exception message returns lots of good information on the subject, which mostly suggests the usual suspects are:

- The client timing out or closing the request connection
- TCP port exhaustion on the server running the application

See here for an example: https://stackoverflow.com/questions/7228703/error-the-i-o-operation-has-been-aborted-because-of-either-a-thread-exit-or-an
